### PR TITLE
Removed skippable related things, since they are moved to somewhere else

### PR DESCRIPTION
**Pull request by rom1mouret**
Must be in sync with:
- ["refactoring" branch](https://github.com/daisy/pipeline-mod-tts/tree/refactoring) of pipeline-mod-tts

### CODE REVIEW

**Comment by rdeltour** [comment]
@rom1mouret why is the deprecated options are kept ? is it to avoid API breaks ?

If this is a long-term definitive change, maybe we can actually remove the option, propagate the API break, and upgrade the major version number. WDYT ?

**Comment by rom1mouret** [comment]
Yes, it is to avoid API breaks. But I'm ok with removing them, after I made sure that there are not used for the HTML break detection.

**Comment by rom1mouret** [comment]
They are not. They are used for the ZedAI break detection though, but the ZedAI part is broken anyway, and not called anywhere.

**Comment by rdeltour** [comment]
they seem to be used in `px:dtbook-break-detect` as well....

**Comment by rom1mouret** [comment]
You're right. I didn't notice that. They can be safely removed from px:dtbook-break-detect, given that even old versions of dtbook-tts of pipeline-mod-tts relies on the default value of `split-skippable`

**Comment by rdeltour** [comment]
I forced push the API-break in a new commit. Can you please review before I squash and merge ? Thx.

**Comment by rom1mouret** [comment]
Sounds good to me.

**Comment by rdeltour** [comment]
Squashed and rebased as fe0cf28

**Pull request closed without merging**
